plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("kapt")
}

android {

    /**
     * Encapsulates signing configurations that you can apply to BuildType and ProductFlavor configurations.
     */
    signingConfigs {

        getByName("debug") {
            keyAlias = "androiddebugkey"
            keyPassword = "android"
            storePassword = "android"
            storeFile = rootProject.file("settings/keystore/debug.jks")
        }

        create("release") {
            keyAlias = "playfinity2018"
            keyPassword = "playfinity2018"
            storePassword = "playfinity2018"
            storeFile = rootProject.file("settings/keystore/release.jks")
        }
    }

    /**
     * Encapsulates all build type configurations for this project.
     */
    buildTypes {

        debug {

            // Specifies whether to enable code shrinking for this build type.
            isMinifyEnabled = false

            // Specifies signing config for this variant.
            signingConfig = signingConfigs.getByName("debug")

            // Specifies version name suffix, that will be appended to the "base"
            // version name when calculating the final version name for this variant.
            versionNameSuffix = " Internal"
        }

        release {

            // Specifies whether to enable code shrinking for this build type.
            isMinifyEnabled = true

            // Specifies signing config for this variant.
            signingConfig = signingConfigs.getByName("release")
        }
    }

    /**
     * Specifies Java compiler options, such as the language level of the Java source code and generated bytecode.
     */
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    /**
     * Specifies the API level to compile your project against.
     */
    compileSdk = 34

    /**
     * Specifies defaults for variant properties that the Android plugin applies to all build variants.
     */
    defaultConfig {
        applicationId = "register.before.production.android"
        minSdk = 21
        targetSdk = 34
        versionCode = 10001
        versionName = "1.0.0"

        // Adds a new generated app name resource's.
        resValue("string", "PFI_APP_KEY", "FRAMEWORK")
        resValue("string", "PFI_DEV_KEY", "INTERNAL")
        resValue("string", "PFI_API_URL", "https://testapps.playfinity.io/")
        resValue("string", "PFI_CLOUD_API_URL", "https://testapps.playfinity.io/")
    }

    /**
     * Specifies module namespace.
     */
    namespace = "io.playfinity.sdk.sample"
}

dependencies {
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
}
